#!/usr/bin/env sh

_program()
{
	core_usesIn build
	core_usesIn travis ci

	core_dependency_requires '*' rm mkdir
	_build_createInitialFatten()
	{
		local groupName="$1"
		local fattenedOutputPath="$build_outputPath"/fattened/"$groupName"
		rm -rf "$fattenedOutputPath"
		mkdir -m 0755 -p "$fattenedOutputPath"
		"$build_fattenPath_default" --verbose $(core_init_verbosity) --repository-path tools/fatten --output-path "$fattenedOutputPath" --bin-path "$binPath" -- fatten
		
		# Override to force use of our fattened fatten
		build_fattenPath="${fattenedOutputPath}${binPath}"/fatten
	}
	
	# We could turn this into a sort of config file that sits in the root of the repository (or in tools)
	core_dependency_requires '*' rm mkdir ln
	build_fattenAndSwaddle()
	{
		local groupName="$1"
		local repositoryPath="$2"
		local binPath="$3"
		shift 3
		
		local swaddlingPath="$repositoryPath"/swaddling
		local bodyPath="$swaddlingPath"/body
		local fattenedOutputPath="$build_outputPath"/fattened/"$groupName"
		local swaddledOutputPath="$build_outputPath"/swaddled/"$groupName"
		
		# fatten to the body path, but keep it outside of the git repository just in case a '.gitignore' file isn't set at body/.gitignore
		rm -rf "$fattenedOutputPath"
		mkdir -m 0755 -p "${fattenedOutputPath}${binPath}"
		if [ -e "$bodyPath" ]; then
			ln -s "$fattenedOutputPath" "$bodyPath"
		fi

		"$build_fattenPath" --verbose $(core_init_verbosity) --repository-path "$repositoryPath" --output-path "$fattenedOutputPath" --bin-path "$binPath" -- "$@"
		"$build_swaddlePath" --verbose $(core_init_verbosity) --swaddling-path "$swaddlingPath" --output-path "$swaddledOutputPath"
	}
	
	build()
	{
		travis_ci_updateGitSubmodulesRecursively
		build_prepareOutput
		
		local binPath="/usr/bin"
		_build_createInitialFatten 'initial-fatten'
		
		build_fattenAndSwaddle 'shellfire' "$(pwd)" "$binPath" paths.d-helper
		build_fattenAndSwaddle 'fatten' "$(pwd)"/tools/fatten "$binPath" fatten
		build_fattenAndSwaddle 'swaddle' "$(pwd)"/tools/swaddle "$binPath" swaddle
	}
}

_program_name='build'
_program_namespace='build'
_program_version='unversioned'
_program_package_or_build=''
_program_copyright='(c) 2014 Raphael Cohn'
_program_licence='MIT'
_program_written_by='Raphael Cohn'
_program_path="$([ "${_program_fattening_program_path+set}" = 'set' ] && printf '%s\n' "$_program_fattening_program_path" || ([ "${0%/*}" = "${0}" ] && printf '%s\n' '.' || printf '%s\n' "${0%/*}"))"
_program_libPath="${_program_path}/lib"
_program_etcPath="${_program_path}/etc"
_program_entrypoint='build'

_program_commandLine_parseInitialise()
{
	local relativeToPath="$(pwd)"
	build_outputPath_default="$relativeToPath"/output
	build_fattenPath_default="$relativeToPath"/tools/fatten/fatten
	build_swaddlePath_default="$relativeToPath"/tools/swaddle/swaddle
}

_program_commandLine_helpMessage()
{
	_program_commandLine_helpMessage_usage="[OPTION]..."
	_program_commandLine_helpMessage_description="Builds shellfire tools, typically under Travis CI"
	_program_commandLine_helpMessage_options="
  -p, --output-path PATH      PATH to build output to.
                              Defaults to one based on current working directory:-
                              $build_outputPath_default
  -f, --fatten-path PATH      PATH to fatten executable.
                              Defaults to one based on current working directory:-
                              $build_fattenPath_default
  -s, --swaddle-path PATH     PATH to swaddle executable.
                              Defaults to one based on current working directory:-
                              $build_swaddlePath_default"
    _program_commandLine_helpMessage_optionsSpacing='     '
	_program_commandLine_helpMessage_configurationKeys="
  build_outputPath       Equivalent to --output-path
  build_fattenPath       Equivalent to --fatten-path
  build_swaddlePath      Equivalent to --swaddle-path
"
	_program_commandLine_helpMessage_examples="
  ./${_program_name}
"
}

_program_commandLine_optionExists()
{
	case "$optionName" in
	
		o|output-path)
			echo 'yes-argumented'
		;;
	
		f|fatten-path)
			echo 'yes-argumented'
		;;
	
		s|swaddle-path)
			echo 'yes-argumented'
		;;
		
		*)
			echo 'no'
		;;
	
	esac
}

_program_commandLine_processOptionWithArgument()
{
	case "$optionName" in
	
		o|output-path)
			core_validate_folderPathIsReadableAndSearchableAndWritableOrCanBeCreated $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			build_outputPath="$optionValue"
		;;
	
		f|fatten-path)
			core_validate_filePathReadableAndExecutable $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			build_outputPath="$optionValue"
		;;
	
		s|swaddle-path)
			core_validate_filePathReadableAndExecutable $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			build_outputPath="$optionValue"
		;;
	
	esac
}

_program_commandLine_validate()
{
	if core_variable_isSet build_outputPath; then
		core_validate_folderPathIsReadableAndSearchableAndWritableOrCanBeCreated $core_commandLine_exitCode_CONFIG 'configuration setting' 'build_outputPath' "$build_outputPath"
	else
		core_message INFO "Defaulting --output-path to '$build_outputPath_default'"
		build_outputPath="$build_outputPath_default"
		core_validate_folderPathIsReadableAndSearchableAndWritableOrCanBeCreated $core_commandLine_exitCode_CONFIG 'default' 'build_outputPath' "$build_outputPath"
	fi
	
	if core_variable_isSet build_fattenPath; then
		core_validate_filePathReadableAndExecutable $core_commandLine_exitCode_CONFIG 'configuration setting' 'build_fattenPath' "$build_fattenPath"
	else
		core_message INFO "Defaulting --fatten-path to '$build_fattenPath_default'"
		build_fattenPath="$build_fattenPath_default"
		core_validate_filePathReadableAndExecutable $core_commandLine_exitCode_CONFIG 'default' 'build_fattenPath' "$build_fattenPath"
	fi
	
	if core_variable_isSet build_swaddlePath; then
		core_validate_filePathReadableAndExecutable $core_commandLine_exitCode_CONFIG 'configuration setting' 'build_swaddlePath' "$build_swaddlePath"
	else
		core_message INFO "Defaulting --swaddle-path to '$build_swaddlePath_default'"
		build_swaddlePath="$build_swaddlePath_default"
		core_validate_filePathReadableAndExecutable $core_commandLine_exitCode_CONFIG 'default' 'build_swaddlePath' "$build_swaddlePath"
	fi
}

. "$_program_libPath"/shellfire/core/init.functions "$@"
