#!/usr/bin/env sh

_program()
{
	hello_world_example()
	{
		printf '%s\n' "Hello World"
	}
}

_program_name='hello-world-example'
_program_version='unversioned'
_program_package_or_build=''
_program_copyright='(c) 2014 Raphael Cohn'
_program_licence='MIT'
_program_written_by='Raphael Cohn'
_program_path="$([ "${_program_fattening_program_path+set}" = 'set' ] && printf '%s\n' "$_program_fattening_program_path" || ([ "${0%/*}" = "${0}" ] && printf '%s\n' '.' || printf '%s\n' "${0%/*}"))"
_program_libPath="${_program_path}/lib"
_program_etcPath="${_program_path}/etc"
_program_entrypoint='hello_world_example'

. "$_program_libPath"/shellfire/core/init.functions "$@"
