#!/usr/bin/env bash

_program()
{
	core_usesIn core/variable array
	
	shellfire_fatten_discoverPackageManagers()
	{
		_shellfire_fatten_discoverPackageManagers_callback()
		{
			if [ ! -s "$filePath" ]; then
				return 0
			fi
			local lengthOf=".functions"
			shellfire_fatten_allPackageManagers="$shellfire_fatten_allPackageManagers $(core_variable_allButLastN "$(core_compatibility_basename "$filePath")" ${#lengthOf})"
		}
		
		shellfire_fatten_allPackageManagers=''
		core_path_iterateOverFolderPath "$_program_libPath"/"$core_libraryName"/core/dependency/check _shellfire_fatten_discoverPackageManagers_callback
	}
	
	# We're supposed to use git's "low-level plumbing" and avoid 'porcelain' commands. Given how hideous git's syntax is, life is too short. We'll fix the bugs that arise instead.
	core_dependency_requires '*' git awk sort date md5sum
	shellfire_fatten_obtainGitDetails()
	{
		pushd "$shellfire_fatten_repositoryPath"
		
			if [ ! -d '.git' ]; then
				core_exitError "--repository-path '$shellfire_fatten_repositoryPath' is not a git repository"
			fi
			
			shellfire_fatten_branch="$(git branch | awk '/^\*/ {print $2}')"
			shellfire_fatten_commit="$(git log -n 1 --format='%H')"
			shellfire_fatten_authors="$(git log --format='%aN' | sort -u | awk 'NR==1 {ORS=""; print $0}; NR>1 {ORS=""; print ", " $0}')"
			local iso8601Date="$(git log -n 1 --format='%ci')"
			shellfire_fatten_version="$(date -d "$iso8601Date" '+%Y.%m.%d.%H.%M')"
			
			if [ "$shellfire_fatten_force" = 'no' ]; then
				local pendingChanges="$(git diff --minimal --no-color --name-status)"
				if [ -n "$pendingChanges" ]; then
					core_exitError $core_commandLine_exitCode_DATAERR "Pending changes in --repository-path '$shellfire_fatten_repositoryPath'"
				fi
				shellfire_fatten_packageOrBuild="$shellfire_fatten_branch commit $shellfire_fatten_commit variant $(git diff --minimal --no-color | md5sum | awk '{print $1}')"
			else
				shellfire_fatten_packageOrBuild="$shellfire_fatten_branch commit $shellfire_fatten_commit"
			fi
			
		popd
	}
	
	shellfire_fatten_createTemporaryFolder()
	{
		local TMP_FOLDER
		core_temporaryFiles_newFolderToRemoveOnExit
		shellfire_fatten_temporaryFolderPath="$TMP_FOLDER"
	}
	
	shellfire_fatten_createOutputFolder()
	{
		mkdir -m 0755 -p "$shellfire_fatten_outputPath" || core_exitError $core_commandLine_exitCode_CANTCREAT "Can not create --output-path '$shellfire_fatten_outputPath'"
		pushd "$shellfire_fatten_outputPath"
		
			shellfire_fatten_outputPath="$(pwd -P)"
		
		popd
	}
	
	core_dependency_requires '*' head bash chmod
	core_snippet_embed raw bootstrap
	shellfire_fatten_fattenProgram()
	{
		local shellfire_fatten_originalProgram="$core_variable_array_element"
		local shellfire_fatten_programPath="$(core_compatibility_dirname "$shellfire_fatten_originalProgram")"
		local shellfire_fatten_programName="$(core_compatibility_basename "$shellfire_fatten_originalProgram")"
		local shellfire_fatten_fattenedProgram="$shellfire_fatten_outputPath"/"$shellfire_fatten_programName"
		local shellfire_fatten_bootstrapProgram="$shellfire_fatten_temporaryFolderPath"/"$shellfire_fatten_programName"
		local shellfire_fatten_shebang="$(head -n 1 "$shellfire_fatten_originalProgram")"
		
		cat >>"$shellfire_fatten_bootstrapProgram" <<-EOF
			$shellfire_fatten_shebang
			set -e
			set -u
			_program_fattening_shebang='$shellfire_fatten_shebang'
			_program_fattening_program_path='$(core_compatibility_dirname "$shellfire_fatten_originalProgram")'
			_program_fattening_originalProgram='$shellfire_fatten_originalProgram'
			_program_fattening_allPackageManagers="$shellfire_fatten_allPackageManagers"

			_program_fattening_program_name="$shellfire_fatten_programName"
			_program_fattening_program_version="$shellfire_fatten_version"
			_program_fattening_program_package_or_build="$shellfire_fatten_packageOrBuild"
			_program_fattening_program_written_by="$shellfire_fatten_authors"
			_program_fattening_program_libPath="$shellfire_fatten_libPath"
			_program_fattening_program_etcPath="$shellfire_fatten_etcPath"
			_program_fattening_program_varPath="$shellfire_fatten_varPath"
		EOF
		core_snippet_retrieve bootstrap >>"$shellfire_fatten_bootstrapProgram"
		
		bash "$shellfire_fatten_bootstrapProgram" >"$shellfire_fatten_fattenedProgram"
		chmod +x "$shellfire_fatten_fattenedProgram"
	}

	shellfire_fatten()
	{
		shellfire_fatten_discoverPackageManagers
		shellfire_fatten_obtainGitDetails
		shellfire_fatten_createTemporaryFolder
		shellfire_fatten_createOutputFolder
		
		core_variable_array_iterate shellfire_fatten_programs shellfire_fatten_fattenProgram
	}
}

_program_name='shellfire-fatten'
_program_namespace='shellfire_fatten'
_program_version='unversioned'
_program_package_or_build=''
_program_copyright='(c) 2014 Raphael Cohn'
_program_licence='MIT'
_program_written_by='Raphael Cohn'
_program_path="$([ "${_program_fattening_program_path+set}" = 'set' ] && printf '%s\n' "$_program_fattening_program_path" || ([ "${0%/*}" = "${0}" ] && printf '%s\n' '.' || printf '%s\n' "${0%/*}"))"
_program_libPath="${_program_path}/../../lib"
_program_etcPath="${_program_path}/../../etc"
_program_varPath="${_program_path}/../../var"
_program_entrypoint='shellfire_fatten'

_program_commandLine_parseInitialise()
{
	# Needed in help text
	_program_default_etcPath='/etc'
	_program_default_libPath='/usr/lib'
	_program_default_varPath='/var'
}

_program_commandLine_helpMessage()
{
	_program_commandLine_helpMessage_usage="[OPTION]... -- [PROGRAMS]..."
	_program_commandLine_helpMessage_description="Fattens shellfire executables so they standalone."
	_program_commandLine_helpMessage_options="
  -r, --repository-path PATH  Path to folder containing a PROGRAM
  -e, --etc-path PATH         Path to install fir etc folder [Default ${_program_default_etcPath}]
  -l, --lib-path PATH         Path to lib folder [Default ${_program_default_libPath}]
  -l, --var-path PATH         Path to var folder [Default ${_program_default_varPath}]
  -f, --force                 Force fattening even if there are uncommited changes
  -o, --output-path PATH      Path to folder (created in necessary) for fattened PROGRAM"
    _program_commandLine_helpMessage_optionsSpacing='     '
	_program_commandLine_helpMessage_configurationKeys="
  shellfire_fatten_etcPath  Equivalent to --etc-path
  shellfire_fatten_libPath  Equivalent to --lib-path
  shellfire_fatten_varPath  Equivalent to --var-path
  shellfire_fatten_repositoryPath  Equivalent to --repository-path
  shellfire_fatten_force  Equivalent to --force (specify yes or no)
  shellfire_fatten_outputPath  Equivalent to --output-path
"
	_program_commandLine_helpMessage_examples="
  ${_program_name} -r git-repo/bin -- minor-test
"
}

_program_commandLine_optionExists()
{
	case "$optionName" in
		
		r|repository-path)
			echo 'yes-argumented'
		;;
		
		e|etc-path)
			echo 'yes-argumented'
		;;
		
		f|force)
			echo 'yes-argumentless'
		;;
		
		l|lib-path)
			echo 'yes-argumented'
		;;
		
		l|var-path)
			echo 'yes-argumented'
		;;
		
		o|output-path)
			echo 'yes-argumented'
		;;
		
		*)
			echo 'no'
		;;
		
	esac
}

_program_commandLine_processOptionWithoutArgument()
{
	case "$optionName" in
		
		f|force)
			shellfire_fatten_force='yes'
		;;
		
	esac
}

_program_commandLine_processOptionWithArgument()
{
	case "$optionName" in
		
		r|repository-path)
			core_validate_folderPathReadableAndSearchable $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			shellfire_fatten_repositoryPath="$optionValue"
		;;
		
		e|etc-path)
			core_validate_pathNotEmpty $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			shellfire_fatten_etcPath="$optionValue"
		;;
		
		l|lib-path)
			core_validate_pathNotEmpty $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			shellfire_fatten_libPath="$optionValue"
		;;
		
		l|var-path)
			core_validate_pathNotEmpty $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			shellfire_fatten_varPath="$optionValue"
		;;
		
		o|output-path)
			core_validate_pathNotEmpty $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			shellfire_fatten_outputPath="$optionValue"
		;;
		
		*)
			echo 'no'
		;;
		
	esac
}

_program_commandLine_handleNonOptions()
{
	if [ $# -eq 0 ]; then
		core_commandLine_exitBadCommandLine "No programs specified"
	fi
	local shellfire_fatten_program
	for shellfire_fatten_program in "$@"
	do
		core_validate_filePathReadableAndExecutableAndNotEmpty $core_commandLine_exitCode_USAGE 'non-options' 'programs' "$shellfire_fatten_program"
		
		cd -P "$(core_compatibility_dirname "$shellfire_fatten_program")" 1>/dev/null
		
			shellfire_fatten_program="$(pwd)"/"$(core_compatibility_basename "$shellfire_fatten_program")"
		
		cd - >/dev/null
		
		core_variable_array_append shellfire_fatten_programs "$shellfire_fatten_program"
	done
}

_program_commandLine_validate()
{
	local optionNameIncludingHyphens
	local optionValue
	
	if core_variable_isUnset shellfire_fatten_force; then
		shellfire_fatten_force='no'
	else
		core_validate_isBoolean $core_commandLine_exitCode_CONFIG 'configuration setting' 'shellfire_fatten_force' "$shellfire_fatten_force"
	fi
	
	if core_variable_isUnset shellfire_fatten_repositoryPath; then
		core_commandLine_exitBadCommandLine "The option '--repository-path (-r)' must be specified"
	else
		core_validate_folderPathReadableAndSearchable $core_commandLine_exitCode_CONFIG 'configuration setting' 'shellfire_fatten_repositoryPath' "$shellfire_fatten_repositoryPath"
	fi
	
	if core_variable_isUnset shellfire_fatten_etcPath; then
		shellfire_fatten_etcPath="$_program_default_etcPath"
	else
		core_validate_pathNotEmpty $core_commandLine_exitCode_CONFIG 'configuration setting' 'shellfire_fatten_etcPath' "$shellfire_fatten_etcPath"
	fi
	
	if core_variable_isUnset shellfire_fatten_libPath; then
		shellfire_fatten_libPath="$_program_default_libPath"
	else
		core_validate_pathNotEmpty $core_commandLine_exitCode_CONFIG 'configuration setting' 'shellfire_fatten_libPath' "$shellfire_fatten_libPath"
	fi
	
	if core_variable_isUnset shellfire_fatten_varPath; then
		shellfire_fatten_varPath="$_program_default_varPath"
	else
		core_validate_pathNotEmpty $core_commandLine_exitCode_CONFIG 'configuration setting' 'shellfire_fatten_varPath' "$shellfire_fatten_varPath"
	fi
	
	if core_variable_isUnset shellfire_fatten_outputPath; then
		core_commandLine_exitBadCommandLine "The option '--output-path (-o)' must be specified"
	else
		core_validate_pathNotEmpty $core_commandLine_exitCode_CONFIG 'configuration setting' 'shellfire_fatten_outputPath' "$shellfire_fatten_outputPath"
	fi
}

# Assumes pwd, and so requires this code to be running from this folder
. "$_program_libPath"/shellfire/core/init.functions "$@"
