#!/usr/bin/env sh
set -e
set -u

installIfCommandNotPresent()
{
	local program="$1"
	shift 1
	
	if command -v "$program" 1>/dev/null 2>/dev/null ; then
		return 0
	fi
	
	printf '%s\n' "Installing $program"
	"$@"
}

installHomebrew()
{
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	brew doctor
	
	# check is /usr/local/{s}bin is on the path
}

installHomebrewDependency()
{
	printf '%s\n' "Updating Homebrew"
	brew update
	
	printf '%s\n' "Upgrading Homebrew"
	brew upgrade
	
	# need to take into account taps... duplicates a lot of logic!!!
	
	local dependency
	for dependency in "$@"
	do
		if ! brew --prefix "$dependency" 1>/dev/null 2>/dev/null; then
			brew install "$dependency"
		fi
	done
}

installRubyGemDependency()
{
	local dependency
	for dependency in "$@"
	do
		# gem help list documentation (2.1.2_3) refers to 'STRING' when it means 'regex'!
		if ! gem list "^${dependency}$" --installed --local 1>/dev/null; then
			gem install "$dependency"
		fi
	done
}

installIfCommandNotPresent brew installHomebrew

installHomebrewDependency \
	ruby \
	bash \
	dash \
	ksh \
	pdksh \
	mksh \
	zsh

installRubyGemDependency \
	travis-lint \
	travis
