#!/usr/bin/env sh

_program()
{
	core_usesIn core/dependency/check Homebrew
	core_usesIn core/dependency/languagePackageManagers Ruby
	macosx_environment_setup()
	{
		core_dependency_check_Homebrew_installPackageManagerIfRequired
		
		core_dependency_check_forcePackageManagerUpgradeDuringInstall=1 core_dependency_check_Homebrew_packageManager \
			ruby \
			bash \
			dash \
			ksh \
			pdksh \
			mksh \
			zsh
		
		core_dependency_languagePackageManagers_Ruby_packageManager \
			travis-lint \
			travis
	}
}

readonly _program_name='macosx-environment-setup'
readonly _program_version='unversioned'
readonly _program_package_or_build=''
readonly _program_copyright='(c) 2014 Raphael Cohn'
readonly _program_licence='MIT'
readonly _program_written_by='Raphael Cohn'
readonly _program_path="$([ "${_program_fattening_program_path+set}" = 'set' ] && printf '%s\n' "$_program_fattening_program_path" || ([ "${0%/*}" = "${0}" ] && printf '%s\n' '.' || printf '%s\n' "${0%/*}"))"
readonly _program_libPath="${_program_path}/../../lib"
readonly _program_etcPath="${_program_path}/../../etc"
readonly _program_entrypoint='macosx_environment_setup'

_program_commandLine_parseInitialise()
{
	core_init_verbosity=1
}

_program_commandLine_helpMessage()
{
	_program_commandLine_helpMessage_description="Sets up build environment for Mac OS X."
}

. "$_program_libPath"/shellfire/core/init.functions "$@"