#!/usr/bin/env sh
# This file is part of shellfire. It is subject to the licence terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/shellfire-dev/shellfire/master/COPYRIGHT. No part of shellfire, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
# Copyright © 2014-2015 The developers of shellfire. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/shellfire-dev/shellfire/master/COPYRIGHT.


_program()
{
	core_usesIn core/dependency/check Homebrew
	core_usesIn core/dependency/languagePackageManagers Ruby
	macosx_environment_setup()
	{
		core_dependency_check_Homebrew_installPackageManagerIfRequired
		
		core_dependency_check_forcePackageManagerUpgradeDuringInstall=1 core_dependency_check_Homebrew_packageManager \
			ruby \
			bash \
			dash \
			ksh \
			pdksh \
			mksh \
			zsh
		
		core_dependency_languagePackageManagers_Ruby_packageManager \
			travis-lint \
			travis
	}
}

_program_name='macosx-environment-setup'
_program_namespace='macosx_environment_setup'
_program_version='unversioned'
_program_package_or_build=''
_program_copyright='(c) 2014 Raphael Cohn'
_program_licence='MIT'
_program_written_by='Raphael Cohn'
_program_path="$([ "${_program_fattening_program_path+set}" = 'set' ] && printf '%s\n' "$_program_fattening_program_path" || ([ "${0%/*}" = "${0}" ] && printf '%s\n' '.' || printf '%s\n' "${0%/*}"))"
_program_libPath="${_program_path}/../../lib"
_program_etcPath="${_program_path}/../../etc"
_program_entrypoint='macosx_environment_setup'

_program_commandLine_parseInitialise()
{
	core_init_verbosity=1
}

_program_commandLine_helpMessage()
{
	_program_commandLine_helpMessage_description="Sets up build environment for Mac OS X."
}

. "$_program_libPath"/shellfire/core/init.functions "$@"