#!/usr/bin/env sh
# This file is part of shellfire shellfire. It is subject to the licence terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/shellfire-dev/shellfire/master/COPYRIGHT. No part of shellfire shellfire, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
# Copyright © 2014-2015 The developers of shellfire shellfire. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/shellfire-dev/shellfire/master/COPYRIGHT.


set -e
set -u

# Directory is root of git repo
chmod 0600 builder/deployment/deploy_key.pem
ssh-add builder/deployment/deploy_key.pem
git remote add release DEPLOY_REPO_URI_GOES_HERE
git config --global push.default simple
git push release
